### ISSUE TITLE
`ZIO.foreachPar(nonEmptyList)(f)` doesn't compile

### ISSUE THREAD

**Issue by guizmaii** [zio/zio-prelude#1120]
That'd be nice if we had a version of `ZIO.foreachPar` that would work for `zio.prelude.NonEmptyList`

This, for now, doesn't compile:
```scala
object Example {
    def f(i: Int): UIO[Int] = ZIO.succeed(i + 1)
    val list                = zio.prelude.NonEmptyList(1, 2, 3)
    val res                 = ZIO.foreachPar(list)(f(_))
}
```
(Issue initially reported here: https://github.com/zio/zio/issues/8070)

**Comment by adamgfraser** [comment]
I think this probably makes more sense as an operator on `NonEmptyList`:

```scala
nonEmptyList.mapZIOPar(f)
```

**Comment by guizmaii** [comment]
Does this operator exist on `List`, `Set`, `Map`, `Chunk`, `NonEmptyChunk`, etc.?

If not, that'll introduce a new way of doing things just for `NonEmptyList` 🤔

**Comment by adamgfraser** [comment]
It exists for `Chunk` and `NonEmptyChunk`. If we control the data type then we provide it as an operator on the data type.
