### ISSUE TITLE
Newtypes: Composed assertions on String values do not work at compile time

### ISSUE THREAD

**Issue by ajaychandran** [zio/zio-prelude#1179]
[Scastie](https://scastie.scala-lang.org/gXNuRFqPRw6cHGJd97OOAA)
```scala
import zio.prelude.{Subtype, Validation}
import zio.prelude.Assertion._

object AB extends Subtype[String]:
  
  override inline def assertion = 
    equalTo("A") || equalTo("B")

type AB = AB.Type

val valid1: AB = AB("A")
val valid2: AB = AB("B")
val oops = AB("C")
```

**Expected**
Compilation error for last variable.
`We were unable to read your assertion at compile-time.`

**Actual**
Compilation error for all 3 variables.

**Version**
1.0.0-RC20

**Comment by guizmaii** [comment]
Did you try with `assertCustom`?

(I'm not sure of the syntax as I'm not using Scala3. You can find the correct syntax in Scala3's zio-prelude test suite)
```scala
object AB extends Subtype[String]:
  
  override inline def assertion = 
    assertCustom { s =>
      if (s == "A" || a == "B") Right(())
      else Left(AssertionError.failure("This is an error message"))
    }
```

**Comment by ajaychandran** [comment]
Thanks. I could not find `assertCustom` in Scala3 but using `SubtypeCustom` [worked](https://scastie.scala-lang.org/eJhfctpZRGe36E0e6z1JIA).

**Comment by guizmaii** [comment]
It's indeed `SubtypeCustom` in Scala3. See https://github.com/zio/zio-prelude/pull/793/files#diff-9a09024c09e541dbd1ceb4c4002dc904a43af1305093ee8ca2152bdf273f0c77R90
