### ISSUE TITLE
The `abstraction-diagrams` ID Doesn't Exist

### ISSUE THREAD

**Issue by khajavi** [zio/zio-prelude#1244]
By running the following two commands:
```
sbt docs/installWebsite
sbt docs/previewWebsite
```

The following error occurs:

```
[ERROR] Loading of version failed for version current
[ERROR] Error: Invalid sidebar file at "sidebars.js".
These sidebar document ids do not exist:
- zio-prelude/abstraction-diagrams

Available document ids are:
- adopters
- caliban-deriving/index
- can_fail
- code-of-conduct
- coding-guidelines
- contributing-to-documentation
- contributor-guidelines
- ecosystem/community/caliban
- ecosystem/community/distage
- ecosystem/community/fhir-indexer
- ecosystem/community/index
- ecosystem/community/logstage
```

I think this is the line that caused this issue: https://github.com/zio/zio-prelude/blob/da8c9e09bf616dd66451327cc5be702aee5f0ea1/docs/sidebars.js#L9

Contributors note: Please make a release after the fix.

**Comment by adamgfraser** [comment]
@sideeffffect Can you take a look at this?

**Comment by sideeffffect** [comment]
I apologize for the issue. I thought we had a check in CI that builds the website... has that changed in the meantime? Or it wasn't ever there to begin with?

**Comment by khajavi** [comment]
@sideeffffect 
No problem! I'm not sure if we had this check from the beginning or not.
But it is advisable to use `zio-sbt-ci` plugin instead, instead of manually written ci. This can help us to be sure that the ci is always updated and consistent through the zio ecosystem.
