### ISSUE TITLE
ForEach.fold[I: Identity] is not exposed in syntax

### ISSUE THREAD

**Issue by SimY4** [zio/zio-prelude#1399]
Not sure what hepened there but `ForEach.fold` is not accessible via syntax extensions.

**Comment by sideeffffect** [comment]
Could you please link some example? The best would be something on https://scastie.scala-lang.org/
Also, can you determine what was the last version this worked?

**Comment by SimY4** [comment]
Hey @sideeffffect . Thanks for coming back to me on this. I meant this snippet here:

```scala
import zio.prelude.*
import zio.prelude.newtypes.*

val l = List(1, 2, 3).map(i => Sum(i))

val f1: Sum[Int] = ForEach[List].fold(l) // works

val f2: Sum[Int] = l.fold // error. not existing
```

Essentially fold is not being exposed as a syntax extension for ForEach eligible types. But it exists on a ForEach typeclass.
