### ISSUE TITLE
ZPure DSL state type parameter issues

### ISSUE THREAD

**Issue by zeal18** [zio/zio-prelude#1425]
Hi all again! I'm trying to model the following logging abstraction using `ZPure`
```scala
import ch.qos.logback.classic.spi.ILoggingEvent
import ch.qos.logback.classic.spi.LoggingEvent
import import ch.qos.logback.classic.Level

def log(level: Level, message: String): ZPure[ILoggingEvent, Any, Nothing, Any, Nothing, Unit] = {
  if (isLogLevelEnabled(level)) {
    val event = LoggingEvent()
    // set fields of the event
      
    ZPure.log(event)
  } else ZPure.unit
}
```
but it doesn't compile because both `ZPure.log` and `ZPure.unit` have the `S` type parameter which define both `S1` and `S2` as exactly the same type and this never matches "-Any, +Nothing"

The compilation errors are
```
Found:    zio.prelude.fx.ZPure[ch.qos.logback.classic.spi.LoggingEvent, S, S, Any, Nothing, Unit]
Required: zio.prelude.fx.ZPure[ch.qos.logback.classic.spi.ILoggingEvent, Any, Nothing, Any, Nothing, Unit]
```
and
```
Found:    zio.prelude.fx.ZPure[Nothing, Any, Any, Any, Nothing, Unit]
Required: zio.prelude.fx.ZPure[ch.qos.logback.classic.spi.ILoggingEvent, Any, Nothing, Any, Nothing, Unit]
```
correspondingly.

Checking the `unit` implementation it's actually uses the correct type under the hood:
```scala
  /**
   * Constructs a computation that always returns the `Unit` value, passing the
   * state through unchanged.
   */
  def unit[S]: ZPure[Nothing, S, S, Any, Nothing, Unit] =
    succeedUnit
```
where the `succeedUnit` is
```scala
private val succeedUnit: ZPure[Nothing, Any, Nothing, Any, Nothing, Unit]            = Succeed(())
```

It looks like other methods like `succeed`, `none`,  `attempt`, `collect` and etc. have the same problem.

I can try to make a PR to update the dsl to improve this, but I would like to know your opinion first, so WDYT?

**Comment by ghostdogpr** [comment]
You can't use `Any, Nothing` for your `log` function because that `ZPure` couldn't be run. It would have to produce an output state of type `Nothing`, which is impossible. 

You should either add a type parameter `S` to your function, or if you never make use of the state you can enforce it to be `Unit, Unit`.

**Comment by zeal18** [comment]
> You can't use `Any, Nothing` for your `log` function because that `ZPure` couldn't be run. It would have to produce an output state of type `Nothing`, which is impossible.
> 
> You should either add a type parameter `S` to your function, or if you never make use of the state you can enforce it to be `Unit, Unit`.

Thank you for the quick response! It makes a lot of sense, but it won't work for my case as well because of another reason.

I'm modeling the following abstraction based on `ZPure`:
```scala
case class State(a: String, b: Int)
sealed trait StateUpdate
object StateUpdate {
  case class UpdateA(newA: String) extends StateUpdate
  case class UpdateB(newB: Int) extends StateUpdate
}

type Effect[+E, +A] = ZPure[LoggingEvent, State, StateUpdate, Any, E, A]
```
so I have an input state, then I run ZPure receiving a description of how to update the state, but the most of methods from the DSL have a single type parameter for the state which makes my case impossible. 

Does it make sense to expose both state type parameters to the DSL?

**Comment by ghostdogpr** [comment]
To be honest personally I always set `S1` and `S2` to be the same, I find it not really usable in any other way.

There was an attempt to use `Unit` as a zero for composition (https://github.com/zio/zio-prelude/issues/462) but it made things even worse so it was rollbacked (https://github.com/zio/zio-prelude/issues/806).

Maybe we could potentially change ZPure to have a single `S`, unless someone has a better way or found how to make it work with different `S1` and `S2`.

**Comment by zeal18** [comment]
> To be honest personally I always set `S1` and `S2` to be the same, I find it not really usable in any other way.
> 
> There was an attempt to use `Unit` as a zero for composition (#462) but it made things even worse so it was rollbacked (#806).
> 
> Maybe we could potentially change ZPure to have a single `S`, unless someone has a better way or found how to make it work with different `S1` and `S2`.

ok, this means that for me it's better to put `StateUpdates` into the resulting type and don't use the state functionality of `ZPure` at all. Does it make sense to keep the state at all? Could be be just replaced by using `R` as an input state and encoding the output state in the output type parameter `A` when needed?

**Comment by ghostdogpr** [comment]
> Does it make sense to keep the state at all? Could be be just replaced by using `R` as an input state and encoding the output state in the output type parameter `A` when needed?

Using the output type would be very annoying and pollute the code. As soon as you modify the state you would have to carry it around and pass it everywhere. I think the State monad is very useful, it just works better with a single state type.

**Comment by zeal18** [comment]
> > Does it make sense to keep the state at all? Could be be just replaced by using `R` as an input state and encoding the output state in the output type parameter `A` when needed?
> 
> Using the output type would be very annoying and pollute the code. As soon as you modify the state you would have to carry it around and pass it everywhere. I think the State monad is very useful, it just works better with a single state type.

You are right. Thank you for your answers and clarifications!
