### ISSUE TITLE
Covariant AssociativeBoth ?

### ISSUE THREAD

**Issue by ahoy-jon** [zio/zio-prelude#182]
While reading the code `AssociativeBoth` is not covariant, but apply ask for a covariant `F[+_]`.

https://github.com/zio/zio-prelude/blob/863236fb015a68219bf3656740de56ad96f7b473/src/main/scala/zio/prelude/AssociativeBoth.scala#L20

https://github.com/zio/zio-prelude/blob/863236fb015a68219bf3656740de56ad96f7b473/src/main/scala/zio/prelude/AssociativeBoth.scala#L33-L34

Is that normal?

**Comment by adamgfraser** [comment]
Good catch. Just submitted a PR to fix.
