### ISSUE TITLE
Improve Traversable syntax so foreach does not clash with List.foreach

### ISSUE THREAD

**Issue by jorge-vasquez-2301** [zio/zio-prelude#206]
Currently, it's not possible to use `foreach` syntax in collections like `List`, because there's already a `List.foreach` method

**Comment by joroKr21** [comment]
Rename it back to `traverse` 😂

**Comment by reibitto** [comment]
Renaming it was brought up in the Discord. John agreed it needs to be renamed.

Are there any other methods that have potential name collisions? Might be worth checking out.

**Comment by sideeffffect** [comment]
This is a problem for the extension method name only. Maybe having a backup name would suffice? `traverse` or `forEach` or `foreach_` or `foreachPrelude`?

**Comment by fanf** [comment]
please, please, don't use `forEach`. It's extremely surprising (inconsistance with all of `ZIO`) and doesn't really address the ambiguty, it's just a technical workaround. Same for `foreach_` which is already used in `ZIO` for something else and is understood (at least by me) like `same as ZIO.foreach, optimized`.

**Comment by joroKr21** [comment]
Yeah `foreach_` is for the case when you don't need the result

**Comment by kitlangton** [comment]
+1 on this. You can wrap the type in question in TraversableOps for now, but it's not quite as nice :)
I'm cool with `traverse` on this, seeing as the type class is `Traversable` anyhow.

**Comment by jdegoes** [comment]
I'm fine with this, we can always add `foreach_` syntax for the `Unit` case. Or maybe go all-in on `forEach`, which is camel-case anyway (unlike `foreach`, which deviates from the usual Scala idiom).

**Comment by kitlangton** [comment]
Solved by #504! Hope it’s cool to close this ;)
