### ISSUE TITLE
Consolidate the implementation of Type class instances

### ISSUE THREAD

**Issue by sideeffffect** [zio/zio-prelude#215]
In the same spirit as https://github.com/zio/zio-prelude/pull/212#issuecomment-673987171 I would like to propose we do that to all other types:
We remove the redundant instances and put the implementation for most concrete Type class to the companion object of the most abstract trait. That way, there's just one, and thus always coherent, implementation for a given Type class hierarchy.
I volunteer to do the work!

What do you guys think?

It is probably a good idea not to do it all at once, but in batches/groups. Any idea what would be the most natural grouping for this endeavor?

---

- [x] https://github.com/zio/zio-prelude/issues/218 `Equal`
- [x] https://github.com/zio/zio-prelude/issues/219 `Associative`
- [x] https://github.com/zio/zio-prelude/issues/220 `AssociativeBoth`
- [x] https://github.com/zio/zio-prelude/issues/282 `AssociativeEither`
- [x] https://github.com/zio/zio-prelude/issues/283 `Invariant`
- [x] https://github.com/zio/zio-prelude/issues/284 `AssociativeFlatten`
- [x] https://github.com/zio/zio-prelude/issues/285 `AssociativeCompose`

**Comment by adamgfraser** [comment]
@sideeffffect Good idea! We can probably break it up into the `Equal` hierarchy, the `Associative` hierarchy, and the `AssociativeBoth` / `AssociativeEither` hierarchies. I am also happy to do some of it.

**Comment by sideeffffect** [comment]
:fireworks: 
awesome work everybody!
:muscle: :muscle: :muscle:
