### ISSUE TITLE
Rethink Newtype.Tag (not only) because of Dotty

### ISSUE THREAD

**Issue by sideeffffect** [zio/zio-prelude#272]
@adamgfraser https://github.com/zio/zio-prelude/pull/246#issuecomment-691368551

> I think the issue with the new types in particular will require more work from us. A relatively minimized reproducer of the issue is below:
> 
> ```scala
> sealed trait NewtypeModule {
> 
>   def newtype[A]: Newtype[A]
> 
>   sealed trait Newtype[A] {
>     type Type
>     def apply(value: A): Type
>   }
> }
> 
> object NewtypeModule {
>   val instance: NewtypeModule =
>     new NewtypeModule {
>       def newtype[A]: Newtype[A] =
>         new Newtype[A] {
>           type Type = A
>           def apply(value: A): Type = value
>         }
>     }
> }
> 
> trait NewtypeExports {
>   import NewtypeModule._
> 
>   abstract class Newtype[A] extends instance.Newtype[A] {
>     val newtype: instance.Newtype[A] = instance.newtype[A]
>     trait Tag
>     type Type = newtype.Type with Tag
>     def apply(value: A): Type = newtype(value).asInstanceOf[Type]
>   }
> }
> 
> object Example extends App with NewtypeExports {
>   
>   object Meter extends Newtype[Double]
>   type Meter = Meter.type
>   
>   Meter(3.4) // class cast exception
> }
> ```
> 
> The problem is that in `NewTypeExports` we define `trait Tag` and then `type Type = new type.Type with Tag`. Then we cast a value of type `A` to a value of type `Type`. `A` is indeed identical to `newtype.Type` so this part of the cast is valid but `Tag` is a completely arbitrary type that we just made up so I don't think it is actually sound to cast `A` to be an instance of this type. It ends up not mattering because `Tag` has no methods defined on it and we never match against `Tag` so we never do anything with it that would be invalid, but I can understand the cast being invalid at this point.
> 
> It seems like to some extent we were relying on an idiosyncracy of the Scala 2 compiler so I don't think we really have a basis for going to the Dotty team and saying there is something wrong here, if anything I think they fixed an incorrect behavior we were relying on for our trick here.
> 
> We probably need to spend some more time on this. We originally added so we could support defining type class instances for new type. Why don't we mark this test as `scala2Only` until we resolve this?
> 
> Copying @jdegoes.

**Comment by regiskuckaertz** [comment]
Isn't this going to be way easier:

```scala
trait Identity[A] {
  def identity: A
  
  extension (x: => A) def <> (y: => A): A
}

object add {
  opaque type Add[A] = A
  
  def apply[A: Numeric, F[_]](xs: F[A]): F[Add[A]] = xs

  given identityAdd[N](using N: Numeric[N]) as Identity[Add[N]]:
    val identity: Add[N] = N.zero

    extension (x: => Add[N]) def <> (y: => Add[N]): Add[N] = N.plus(x, y)
}

object mul {
  opaque type Mul[A] = A

  given identityMul[N](using N: Numeric[N]) as Identity[Mul[N]]:
    val identity: Mul[N] = N.one

    extension (x: => Mul[N]) def <> (y: => Mul[N]): Mul[N] = N.times(x, y)
}

extension [A: Identity] (xs: List[A]) def foldM: A = xs.foldLeft(summon[Identity[A]].identity)(_ <> _)

@main def hello: Unit = {
  import add.{ given _, _ }
  println("result is " + add(List(1, 2, 3, 4, 5, 6)).foldM)
}
// prints 21
```
