### ISSUE TITLE
 Document the Type Class hierarchies with chart: AssociativeBoth

### ISSUE THREAD

**Issue by sideeffffect** [zio/zio-prelude#324]
Document the `AssociativeBoth` hierarchy in a visual way.

parent issue: https://github.com/zio/zio-prelude/issues/321

Have a look at the parent issue for the description of the task. Here's the skeleton of the Mermaid documentation to implement:

    ```mermaid
    classDiagram
      AssociativeBoth~F<_>~ <|-- CommutativeBoth~F<_>~
      AssociativeBoth~F<_>~ <|-- IdentityBoth~F<_>~
      class AssociativeBoth~F<_>~{
      }
      class CommutativeBoth~F<_>~{
      }
      class IdentityBoth~F<_>~{
      }
    ```

**Comment by OldKosherCheese** [comment]
I would like to work on this one.

**Comment by sideeffffect** [comment]
Hello @OldKosherCheese, thanks for choosing to work on this ticket :+1: As is written in the description, a documentation ticket like this might not seem like much, but for us, it is actually _very_ valuable.
Can we somehow help you push this over the finishing line?

**Comment by OldKosherCheese** [comment]
Hi,
@sideeffffect  I have put a draft.
I will put the link for the pic later.

At the moment I am not sure how instances types should be documented for the typeclass as it works on higher type.
Also IdentityBoth instances are defined in AssociativeBoth file. Is there any reason fro that?

**Comment by sideeffffect** [comment]
Nice, I've already commented on the PR.
We're still settling down the conventions on how to document these more advanced cases, but it's already shaping up. Please let me know, if my comments were not intelligible.

> Also IdentityBoth instances are defined in AssociativeBoth file. Is there any reason fro that?

I'm glad you ask :) it's so that Scala implicit resolution mechanism can find that instance regardless if it's looking for a mere `AssociativeBoth` or specifically `IdentityBoth` -- but it's always just one instance = object. And so it has to be in the companion object of the most parent (if that make any sense :joy: ) type class.

This article explains it better: https://meta.plasm.us/posts/2019/09/30/implicit-scope-and-cats/
