### ISSUE TITLE
 Document the Type Class hierarchies with chart: AssociativeEither

### ISSUE THREAD

**Issue by sideeffffect** [zio/zio-prelude#326]
Document the `AssociativeEither` hierarchy in a visual way.

parent issue: https://github.com/zio/zio-prelude/issues/321

Have a look at the parent issue for the description of the task. Here's the skeleton of the Mermaid documentation to implement:

    ```mermaid
    classDiagram
      AssociativeEither~F<_>~ <|-- CommutativeEither~F<_>~
      AssociativeEither~F<_>~ <|-- IdentityEither~F<_>~
      class AssociativeEither~F<_>~{
      }
      class CommutativeEither~F<_>~{
      }
      class IdentityEither~F<_>~{
      }
    ```

**Comment by ernestochero** [comment]
@sideeffffect I would like to take this issue.

**Comment by sideeffffect** [comment]
closed in https://github.com/zio/zio-prelude/pull/418
