### ISSUE TITLE
 Document the Type Class hierarchies with chart: AssociativeCompose

### ISSUE THREAD

**Issue by sideeffffect** [zio/zio-prelude#329]
Document the `AssociativeCompose` hierarchy in a visual way.

parent issue: https://github.com/zio/zio-prelude/issues/321

    ```mermaid
    classDiagram
      AssociativeCompose~:=>[-_, +_]~ <|-- IdentityCompose~:=>[-_, +_]~
      class AssociativeCompose~:=>[-_, +_]~{
      }
      class IdentityCompose~:=>[-_, +_]~{
      }
    ```

**Comment by sideeffffect** [comment]
Note that this has already open PR :point_up:

**Comment by ernestochero** [comment]
@sideeffffect 
Is possible to take this, what is the status of #358 ?

**Comment by sideeffffect** [comment]
Hopefully close to merging. But worry not, there are other, very similar documentation tickets. Look at the parent issue. It would immensely help us if you documented a Type class hierarchy that hasn't been documented yet.

I'm here for you, if you'd need any help with it :wink:
