### ISSUE TITLE
Port ZIO Prelude to Scala.js

### ISSUE THREAD

**Issue by sideeffffect** [zio/zio-prelude#369]
_Difficulty: Intermediate, prior experience with (porting to) Scala.js is an advantage_

Add sbt setup for building, testing and publishing ZIO Prelude for Scala.js 1.x for all Scala 2.11, 2.12 and 2.13.
Have a look at ZIO's https://github.com/zio/zio/blob/master/build.sbt#L130 (`coreJS`, for example) and https://github.com/zio/zio/blob/master/.circleci/config.yml to see how it's done. (Other files of interest are `project/BuildHelper.scala` and `project/plugins.sbt`, but the necessary changes to the should be already in place.)

Once the PR is merged, we should see `zio-prelude_sjs1_2.11`, `zio-prelude_sjs1_2.12` and `zio-prelude_sjs1_2.13` at
https://oss.sonatype.org/content/repositories/snapshots/dev/zio/

**Comment by vigoo** [comment]
I'm doing this

**Comment by mschuwalow** [comment]
@vigoo sorry for not claiming this :(. Just opened a PR that closes this.

**Comment by vigoo** [comment]
Don't worry about it,  you finished faster :)

**Comment by sideeffffect** [comment]
@vigoo don't let this let you down! The ticket for porting to Scala Native is still up for grabs :wink:

**Comment by vigoo** [comment]
maybe a bit later :)
