### ISSUE TITLE
Port ZIO Prelude to Scala Native

### ISSUE THREAD

**Issue by sideeffffect** [zio/zio-prelude#370]
_Difficulty: Intermediate, prior experience with (porting to) Scala Native is an advantage_

Add sbt setup for building, testing and publishing ZIO Prelude for Scala Native `0.4.0-M2` for Scala 2.11.
Have a look at ZIO's https://github.com/zio/zio/blob/master/build.sbt#L133 (`coreNative`, for example) and https://github.com/zio/zio/blob/master/.circleci/config.yml to see how it's done. (Other files of interest are `project/BuildHelper.scala` and `project/plugins.sbt`, but the necessary changes to the should be already in place.)
You can also look at some of the PRs that added Scala Native support to ZIO: https://github.com/zio/zio/pull/4307 , https://github.com/zio/zio/pull/4252 , https://github.com/zio/zio/pull/4260

Once the PR is merged, we should see `zio-prelude_native0.4.0-M2_2.11` at
https://oss.sonatype.org/content/repositories/snapshots/dev/zio/

**Comment by vigoo** [comment]
Seems like `zio_native0.4.0-M2_2.11` depends on `zio-stacktracer_native0.4.0-M2_2.11` (https://search.maven.org/artifact/dev.zio/zio_native0.4.0-M2_2.11/1.0.3/jar) and it's not published at all. So first this dependency should be published from `zio`.

**Comment by sideeffffect** [comment]
Yeah, stacktraces is only published as a snapshot
https://oss.sonatype.org/content/repositories/snapshots/dev/zio/zio-stacktracer_native0.4.0-M2_2.11/

That could help you at least with making the chages to the build setting -- even though we will most likely need to wait for ZIO 1.0.4 to merge your pull request. But having such a prepared PR would still help us immensely, basically all the work will be done :bow:
