### ISSUE TITLE
Add method bothPar to the type class CommutativeBoth

### ISSUE THREAD

**Issue by sideeffffect** [zio/zio-prelude#371]
_Difficulty: Easy, familiarity with the Type class design pattern is an advantage_

After adding `bothPar` to `CommutativeBoth`, implement it for all the types implementing the Type class. The signature is like this:

```scala
  /**
   * Combines two values of types `F[A]` and `F[B]` in a parallel manner to produce an `F[(A, B)]`.
   */
  def bothPar[A, B](fa: => F[A], fb: => F[B]): F[(A, B)]
```

Make sure, that the other helper and extension methods (like `zipPar`) in `CommutativeBoth` use `bothPar` instead of just `both`. Note, that for some types, `bothPar` can be the same implementation as `both`.

As a stretch goal, move the `CommutativeBoth` instances (all that can be, which are all in this case) to the supre-classes' `AssociativeBoth` companion object. Read about the reasoning where to put Type class instance and the _Implicit scope_ in this article https://meta.plasm.us/posts/2019/09/30/implicit-scope-and-cats/

As a stretch goal # 2, add tests for missing instances to `CommutativeBothSpec` (tests for some basic instances, like `Option` or `List` are already present).

**Comment by visar** [comment]
I would like to tackle this.

**Comment by sideeffffect** [comment]
closing as per https://github.com/zio/zio-prelude/issues/372#issuecomment-744067514
