### ISSUE TITLE
Add repeat method to Identity

### ISSUE THREAD

**Issue by lemastero** [zio/zio-prelude#386]
_Difficulty: Easy_

Add method repeat to Identity that will combine input n elements a.
If n is below 1 it should return `identity` element.
```scala
def repeat(a: A, n: Int): A = ???
```

**Comment by shankarshastri** [comment]
@sideeffffect , I would like to give it a try for this hackathon

**Comment by shankarshastri** [comment]
@sideeffffect , I was trying to go through Identity, should the implementation be inside the Identity trait?

```scala
trait Identity[A] extends Associative[A] {

  /**
   * The identity element.
   */
  def identity: A
  
  @tailrec
  final def repeat[A](a: A, n: Int): A = {
    if(n < 1) combine(a, identity)
    else repeat(combine(a, a), n - 1)
  }
}
```

**Comment by sideeffffect** [comment]
@shankarshastri I like this! Especially the part where we reuse the code and thus guarantee consistent behavior of `repeatOption` and `repeat` :+1: 
But there's a catch, if my eyes aren't failing me :smiley: 
The provided implementation of `repeatOption` repreduces the `a` exponentially. If we start with `"a"`, then we will have.
 * `"a"`
 * `"aa"`
 * `"aaaa"`
 * `"aaaaaaaa"`

I think the fix here would be to have a separate variable for the original value to reproduce and another variable for the accumulator.

But you can start your PR with this verbatim and then add tests and then we'll see, either on your machine locally or in CircleCI :wink:
