### ISSUE TITLE
add ZivariantSyntax to package object prelude

### ISSUE THREAD

**Issue by lemastero** [zio/zio-prelude#389]
Difficulty: Easy

ZivariantSyntax needs to be added to package object prelude.
See: https://github.com/zio/zio-prelude/blob/master/src/main/scala/zio/prelude/package.scala#L33

**Comment by shankarshastri** [comment]
I was trying to work on this one as it was a small change as well.

But wanted to know what should the type name be?

```scala
type Zifunctor[:=>[-_, +_, +_]] = Zivariant[:=>]
```
    
Please let me know your thoughts.
@lemastero , @sideeffffect

**Comment by sideeffffect** [comment]
@lemastero What do you think? :)

**Comment by lemastero** [comment]
AFICT There is no need to add alias. Current aliases like:
```scala
type Profunctor[:=>[-_, +_]] = Divariant[:=>]
type Bifunctor[:=>[+_, +_]]  = Bicovariant[:=>]
```
are because there are abstractions Profunctor, Bifunctor in cats.

**Comment by shankarshastri** [comment]
@lemastero , makes sense !!
Removing the alias from PR 👍
