### ISSUE TITLE
Add compose to Covariant

### ISSUE THREAD

**Issue by lemastero** [zio/zio-prelude#390]
Difficulty: Intermediate

Add compose operator that will allow to nest two different Covariant
```scala
def compose[G[+_]: Covariant]: Covariant[({ type lambda[+A] = F[G[A]]})#lambda] =
```

allowing us to write: `val listOptionCovariant = Covariant[List] compose Covariant[Option]`

**Comment by GrigoriyDmitriev** [comment]
@lemastero , I can work on this one for zio-hackathon.

Also, it looks like the example implies signature
`def compose[G[+_]](g: Covariant[G]): Covariant[({ type l[+A] = F[G[A]] })#l]`
Which one to implement?

**Comment by sideeffffect** [comment]
I think `def compose[G[+_]](g: Covariant[G]): Covariant[({ type l[+A] = F[G[A]] })#l]` is the correct thing :wink:

**Comment by sideeffffect** [comment]
@lemastero Would it make sense to provide `compose` also for `Contravariant`? Or even `Invariant`?

**Comment by lemastero** [comment]
@sideeffffect yes you can compose Contravariant and Invariant functors. Maybe in a separate ticket.

**Comment by sideeffffect** [comment]
Would you like to create them @lemastero ? :smile_cat:

**Comment by lemastero** [comment]
Done: #402 #403

**Comment by lemastero** [comment]
Done in #404
