### ISSUE TITLE
Use CanFail and NeedsEnv For ZPure

### ISSUE THREAD

**Issue by adamgfraser** [zio/zio-prelude#401]
In ZIO we created `CanFail` and `NeedsEnv` data types that can be added as implicit parameters to error handling or environment providing methods to trigger a warning to the user if they are user an error handling operator on an effect that can't fail or providing an environment to an effect that doesn't need one. We should add the same thing to `ZPure` operators that handle errors or provide the environment.

**Comment by spoltier** [comment]
I'd like to give this one a try.

**Comment by adamgfraser** [comment]
@spoltier Great!

**Comment by spoltier** [comment]
I have a PR open (some checks still running): #406
