### ISSUE TITLE
Add method multiplyOption to Associative and multiply to Inverse

### ISSUE THREAD

**Issue by sideeffffect** [zio/zio-prelude#417]
The methods are have to have the following signature:
```scala
Associative {
  def multiplyOption(n: Int)(a: A): Option[A] = ???
}
Inverse {
  def multiply(n: Int)(a: A): A = ???
  def multiplyOption(n: Int)(a: A): Some[A] = Some(multiply(n)(a))
}
```
The methods implementation will such that
```scala
multiply(n) <> multiply(m)  ===  multiply(n + m)
```
That means that in
 * `Associative`, `multiplyOption` will return `None` for `n` <= 0
 * `Identity`, `multiplyOption` will return `None` for `n` < 0 and for 0 it will return `Some(identity)`
 * `Inverse`, if `n` < 0, `multiply` will utilize the `inverse` method, e.g. for `n` = 2, it will return `inverse(inverse(identity, a), a)`

related: https://github.com/zio/zio-prelude/issues/386 https://github.com/zio/zio-prelude/issues/387

_EDIT: use currying_

**Comment by shankarshastri** [comment]
@sideeffffect , I shall try to tackle this one.

**Comment by shankarshastri** [comment]
@sideeffffect , will multiply directly use multiplication, or will it use combine, inverse? Bit confused.

**Comment by sideeffffect** [comment]
I've added a comment to the PR, I hope it's clear now. If not, let me know! :wink:
