### ISSUE TITLE
Declaring instances in Scala 3

### ISSUE THREAD

**Issue by regiskuckaertz** [zio/zio-prelude#477]
I've been looking at the immense work that @adamgfraser , @sideeffffect and their fellows have put into organising the typeclasses and especially their instances with both admiration and sadness. I have this feeling that I can perhaps imagine what your thoughts are as you are going through the process of bubbling up all those instances at the root of the hierarchy which I can summarise as: _wtf am I wasting my time with that sh\*\*\*_?

I will skip straight to the particular point of interest for this project: encoding type classes. My first attempt to raise awareness of how inept the Scala language is at this has failed to gather attention:

https://contributors.scala-lang.org/t/encoding-type-class-hierarchies/4626

... that's why I direct it to you. I'll be humbled if you tell me I'm wrong here, but after giving this enough time to marinate my only conclusion is that the only possible solution for encoding type classes is one that flies in the face of all the good software principles that we have learned over the years: separation of concerns, modularity, DRY, ... 

Somehow this project has pulled off an implementation that is leaner and cleaner than anything else, but with a great effort and discipline: not everyone will have the same success. And look at that:

https://github.com/typelevel/cats/blob/master/core/src/main/scala/cats/instances/future.scala#L9-L48
https://github.com/scalaz/scalaz/blob/master/core/src/main/scala/scalaz/std/Either.scala#L27-L86

To me this is a sign of "design smell", that a developer has to work around language features rather than the language imposing that the most obvious solution is also the most elegant one. I don't know how to summarise it otherwise than:

**Co-opting class inheritance for type class extension is _wrong_. Type class extension should be based on the same mechanics used for synthesising instances: implicit resolution.**

If you think this is nonsense, just close this ticket. If there is an ounce of truth there, please help me make some noise in the link above :)

**Comment by sideeffffect** [comment]
Responded :+1: 

At this moment, I feel like what we have is a local optimum, so I wouldn't be eager to change it.

But it would be awesome development, not just for ZIO Prelude, but for the whole Scala world, if we could find the mythical global optimum. But that would need much experimentation.

**Comment by sideeffffect** [comment]
You @regiskuckaertz have been in the Scala game much longer than me, why don't you try to reach directly to the Scala gurus from ScalaZ, cats, the Scala team, @jdegoes and whoever else you might know. I too would be really interested what they have to say about it :wink:

**Comment by regiskuckaertz** [comment]
Thanks @sideeffffect I liked a lot what you said. Will keep on working on that and if I have anything useful to add, I'll raise again.
