### ISSUE TITLE
Consider changing the associativity in AssociativeCompose

### ISSUE THREAD

**Issue by sideeffffect** [zio/zio-prelude#481]
Currently, the type parameter is
```scala
AssociativeCompose[:=>[-_, +_]]
```
which means that it is left associative, but it should be right associative:
```scala
AssociativeCompose[=>:[-_, +_]]
```

so that `a =>: b =>: c =>: ...` = `a =>: (b =>: (c =>: ...))`

https://www.scala-lang.org/files/archive/spec/2.12/06-expressions.html#prefix-infix-and-postfix-operations

blocked on https://github.com/zio/zio-prelude/pull/358

**Comment by jdegoes** [comment]
Good idea!
