### ISSUE TITLE
Introduce ZIO Test-independent validations

### ISSUE THREAD

**Issue by jdegoes** [zio/zio-prelude#482]
For smart constructors, we need an assertion-like entity that produces human English readable errors, with easy overriding of error messages. We should also think about making this Scala 3.0 compatible, in the sense that the encoding should permit us to check literals at compile-time in the Scala 3 sources for the feature.

The goal of this ticket is to remove dependency on ZIO Test from production code, improve error messages, and ensure stronger Scala 3 compatibility.

**Comment by jorge-vasquez-2301** [comment]
@jdegoes I'll work on this one

**Comment by adamgfraser** [comment]
Closed by #743.
