### ISSUE TITLE
Investigate alternative encoding of type classes

### ISSUE THREAD

**Issue by jdegoes** [zio/zio-prelude#485]
<https://contributors.scala-lang.org/t/encoding-type-class-hierarchies/4626/6>

**Comment by sideeffffect** [comment]
Here's the "original" ticket
https://github.com/zio/zio-prelude/issues/477

**Comment by sideeffffect** [comment]
@regiskuckaertz has come up with a very interesting scheme, but it doesn't work in Scala 2, which we probably wouldn't want to drop very soon.

**Comment by jdegoes** [comment]
Actually when I saw the latest version, I became convinced it can be done in Scala 2.x.

**Comment by sideeffffect** [comment]
:thinking: How would we work around Scala 2's lack of `export`?
I'm not saying it's not possible, I just don't see any obvious way right now, but I'd be excited to see what tricks can we teach Scala 2 :+1:

**Comment by jdegoes** [comment]
It's called copy/paste/decorate. 😄 Since the cost is only born by library authors, and rather infrequent, it's acceptable IMO.

Not saying we should definitely do this encoding, only that it is achievable in 2.x.

**Comment by regiskuckaertz** [comment]
Awesome that you are considering it ❤️ 💪 Yes, the Scala 2 version (which incidentally would also be Scala 3) would be more verbose sadly. Give me some time, I'll try it out this weekend.

**Comment by regiskuckaertz** [comment]
Unfortunately there is a cost for users that I did not expect, see the PR for details. Scala crushes my hopes 💣

**Comment by sideeffffect** [comment]
This was still an interesting journey! It was definitely worth it, even if we don't adopt this new encoding right now, because we learned something new, and who knows what value will we/somebody else recover from your experiment 5 years from now.
So don't let this let you down :muscle: :muscle: :muscle:

**Comment by regiskuckaertz** [comment]
Yeah. Have to admit it felt great to be able to write instances where they make sense. Gonna close this, feel free to reopen if you disagree that the experiment failed.

**Comment by adamgfraser** [comment]
I don't think one approach is any more Scala idiomatic than the other, or, at least with where we are landing, that we are inventing any new patterns. The advice we give everyone regarding type classes is to either define them in the companion object of the data type or the type class, which is what we originally did and are talking about coming back to.

The approach above works though it requires defining a trait in addition to a value for every type class instance, which is quite a lot, especially considering that I don't think we would want users to extend these traits.

An alternative would be to just alias the instance we have already defined in the companion objects to the other functional abstractions. This would ensure that a user would find an instance in the expected place, though the implementation would just point to the existing one.

I tend to think however that we should just implement the logic in the companion objects to each of the functional abstractions. Most instances don't have significant logic in them themselves (e.g. the ones above are just implemented in terms of existing set operators) and any such logic could always be extracted to a private method. And I think this would make the code more modular and also easier for people to understand.
