### ISSUE TITLE
Offer a unit and as sugar methods to Validation

### ISSUE THREAD

**Issue by phderome** [zio/zio-prelude#536]
I found myself using `Validation.fromPredicate(a: => A)(p: A => Boolean)` with a reasonably complex `A` but I don't care about the return the value, I just need it to evaluate predicate `p`. It seems like user API would be more complete with the helpers we often see in ZIO such as `unit` and `as`.

**Comment by sideeffffect** [comment]
@phderome I suspect that you might be using an old version of ZIO Prelude. Please check out the newest version: https://github.com/zio/zio-prelude/releases/tag/v1.0.0-RC2
`Validation` has been superseded by `ZPure`, which you can think of as a generalized Validation. (Although Validation is still available as an alias.)
Here are examples how to use it:
https://github.com/zio/zio-prelude/blob/505d001282db74f2df7ffe83bfbca4c3c70db206/core/shared/src/test/scala/zio/prelude/fx/ZPureSpec.scala#L846-L874

**Comment by phderome** [comment]
oh thanks, I didn't realize that!

**Comment by sideeffffect** [comment]
If you excuse my curiosity, may I ask what you're using ZIO Prelude for? Is it a github.com/zio project? Or your own?

**Comment by phderome** [comment]
> If you excuse my curiosity, may I ask what you're using ZIO Prelude for? Is it a github.com/zio project? Or your own?

corporate use. The initial motivation was newtypes and now Validation.

**Comment by sideeffffect** [comment]
:+1: Awesome, I hope it works well for you. If there are also some things that don't work well for you, please share negative feedback too! We want to make Prelude the best :smile_cat:
