### ISSUE TITLE
Some additions to ForEach

### ISSUE THREAD

**Issue by regiskuckaertz** [zio/zio-prelude#629]
How about adding those?
```scala
trait ForEach[F[+_]]:
  def collect[A, B](pf: PartialFunction[A, B]): F[A] => F[B]
  def unzip[A, B]: F[(A, B)] => (F[A], F[B])
```

**Comment by sideeffffect** [comment]
`unzip` could work on a mere `Covariant`, since you just need a `map`, right?
If `collect` is possible, then :+1:

**Comment by adamgfraser** [comment]
We should definitely add `collect`.

The issue with `unzip` I think is as @sideeffffect says above it requires just `Covariant` but if the structure is effectual it involves evaluating the structure twice. This is fine if the structure is a list but perhaps less intuitive if it is a `ZIO`.
