### ISSUE TITLE
Implement partition operations using `Alternative` and a form of `Foldable`

### ISSUE THREAD

**Issue by afsalthaj** [zio/zio-prelude#709]
Given a abstraction like `Foldable`, and `Bifoldable` (or through some other mechanisms given its absence in the library for now), we would need operations such as follows:

1. `partitionEither`

Given `F[A]`, being able to decide on each value of `A` to get either a `LeftB]` or `Right[C]`, and accumulate results on both ends using `Foldable[F]` and `Alternative[F]` to produce `(F[B], F[C])`. In the absence of `Foldable` due to lack of laws, we will need to do some concrete implementations, probably using`Traverse`.

2. Extend it to `partitionEitherM` to produce `M[(F[B], F[C])]` given a Monad[M], such that this can be returned in a `Task` if needed.

3. `partitionFoldBoth`. Could we have unlawful package and feed it in  with `Foldable` and `Bifoldable` ? Example: It can easily allow us to have `partitionFoldBoth `?

```sala

  // The pair of values (`Both` part) can happen inside an `H` (Ex: `Const`, `Either`) which ultimately, which gets pealed off in the out. Example: implement `partitionEither` in terms of `partitionFoldBoth`
  def partitionFoldBoth[F[_, _], B, C](fa: F[A])( f: A => H[B, C])(implicit A: Alternative[F], F: Foldable[F], H: Bifoldable[H]): (F[B], F[C]) = ???
```

4. Extend 3 to support `Monad`ic result returning `G[(F[B], F[C])]` allowing us to return everything in `ZIO` for example.

These operations can be super handy, and this will turn out to be easy to deal with for users, given some good examples.

Please excuse if these operations are handled in a different way already by the library.

**Comment by adamgfraser** [comment]
@afsalthaj Yes would be great to add these. Will work on this.
