### ISSUE TITLE
Proposal to revert the changes in ZPure with State = Unit

### ISSUE THREAD

**Issue by ghostdogpr** [zio/zio-prelude#806]
I am working on a project where all the business logic is written using `ZPure`. While trying to upgrade to RC7, I observed multiple problems with the changes on `ZPure`:
- Unlike `Any` and `Nothing` used in most ZIO data types, `Unit` is not a valid value for any user type, which causes a lot of problems. Even basic code like`if (cond) myZPure else ZPure.succeed(1)` doesn't compile because `ZPure.succeed(1)` has `Unit` and `myZPure` doesn't. Basically `flatMap` eliminates `Unit` but there are many more cases than `flatMap` that are not addressed by this encoding.
- Since `ZPure` has a very long signature, it is common to use aliases but again, any function that returns `Unit` for `S` won't match the expected alias with another `S`. Same when you implement an interface.
- This forces you to add calls to `ZPure.const[S]` or `ZPure.get[S]` everywhere in order to trigger the flatMap that changes `Unit` into the proper `S`. This hurts code readability a lot as well as performance.
- Because `flatMap` is not directly defined on `ZPure` but as an extension method, it doesn't take precedence when you have other imports with a `flatMap`, for example cats. It tries to use the one from cats instead of the one from `ZPure`.

For these reasons, I would like to suggest going back to the old encoding. I don't see how I could migrate my existing codebase with all these problems (in particular the first one, that is quite fundamental) and would have no other choice than to fork it.

**Comment by adamgfraser** [comment]
Yes I agree the current situation is not acceptable.
