### ISSUE TITLE
Subtype of Newtype cause cyclic subtyping error

### ISSUE THREAD

**Issue by gaspb** [zio/zio-prelude#817]
Hi,

Until RC8 we could do subtypes of newtypes 
```scala 
 object GenericItemId extends Newtype[UUID]
 type GenericItemId = GenericItemId.Type

 object SpecificItemId extends Subtype[GenericItemId]
 type SpecificItemId = SpecificItemId.Type
```

This is a pattern we use a lot, sometimes with multiple nesting levels.

Since RC8, this fails with 

```
cyclic aliasing or subtyping involving type Type
type GenericItemId = GenericItemId.Type
```

**Comment by gurinderu** [comment]
It fails with scala 2 and works with scala 3.
Small example https://scastie.scala-lang.org/lGmEDrGCQbeB6kNdzZHgUg

**Comment by adamgfraser** [comment]
@kitlangton Could you take a look at this when you get the chance?

**Comment by mbaechler** [comment]
any idea if this use case will be supported again in the future?

**Comment by kitlangton** [comment]
👍 I will look into this. It definitely should be supported.

**Comment by strokyl** [comment]
:+1:

**Comment by thiloplanz** [comment]
Related question: How does one write an `assertion` in this scenario?

**Comment by kitlangton** [comment]
On this 👍

**Comment by kitlangton** [comment]
Ready 2 go!https://github.com/zio/zio-prelude/pull/949
