### ISSUE TITLE
Add annotations to Recursive via ZEnvironment

### ISSUE THREAD

**Issue by jdegoes** [zio/zio-prelude#850]
`Recursive` can have a `annotations` field which is a `ZEnvironment`, initially empty. This will facilitate adding arbitrary type-directed annotations to nodes of a recursive structure.

/cc @DamianReeves

**Comment by adamgfraser** [comment]
Will add this.

**Comment by DamianReeves** [comment]
After some discussion with Adam it feels like a data type which knows how to combine annotations is needed. I pushed up a first pass at this.

**Comment by adamgfraser** [comment]
The `AnnotationMap` approach with an associative combining operation is certainly a valuable one for specific cases. I wonder if we should stick with the `ZEnvironment` approach here, which I think is a bit more general (basically just supporting having the concept of multiple annotations).

The annotation map approach could be used by implementers of specific recursive data types when they wanted the properties that went along with it (e.g. primitive annotations only exist at the "leaves" and annotations at the "branches" are always result of composition of the corresponding leaves).

**Comment by DamianReeves** [comment]
Good point. I am working on a couple of examples of tree structures which we would want to annotate, maybe these use-cases will help us settle on an API.

**Comment by DamianReeves** [comment]
> The `AnnotationMap` approach with an associative combining operation is certainly a valuable one for specific cases. I wonder if we should stick with the `ZEnvironment` approach here, which I think is a bit more general (basically just supporting having the concept of multiple annotations).

Is it maybe possible to combine the `AnnotationMap` and `ZEnvironment` into one `Annotations` data structure which supports both scenarios?

**Comment by adamgfraser** [comment]
I think you could build that logic on top of `ZEnvironment` by defining a function `(ZEnvironment[Annotations], ZEnvironment[Annotations]) => ZEnvironment[Annotations]`.
