### ISSUE TITLE
Unable to use extensions for NewtypeF

### ISSUE THREAD

**Issue by ajaychandran** [zio/zio-prelude#878]
The following [example](https://scastie.scala-lang.org/z96qOAdQRC6ne0KG7Rd7Bw) fails to compile.

```scala
import zio.prelude._

type PropF[+A] = PropF.Type[A]
object PropF extends NewtypeF {

  implicit class PropInt(private val self: Type[Int]) extends AnyVal {

    def next: Type[Int] =
      wrap(unwrap(self) + 1)
  }

  implicit class PropNumeric[+A](private val self: Type[A]) extends AnyVal {

    def increment(implicit N: Numeric[A]): Type[A] =
      wrap(N.plus(unwrap(self), N.one))
  }
}


val pf1: PropF[Int] = PropF(1)
val pf2: PropF[Int] = pf1.next  // compile error: value next is not a member of Playground.PropF[Int]
val pf3: PropF[Int] = pf1.increment  // compile error: value increment is not a member of Playground.PropF[Int]
```

Is this usage incorrect/unsupported?

**Comment by adamgfraser** [comment]
@ajaychandran You just need to do `import PropF._`.

**Comment by ajaychandran** [comment]
Thanks @adamgfraser.

Adding an import statement does resolve the issue but it impacts usability adversely. 
I am trying to define new operators so that no extra imports are required (this [works](https://scastie.scala-lang.org/8CQFMflmQ3ChgCdKFhG0Mw) for `Newtype` instances). Is it not possible to do the same with `NewtypeF`?
