### ISSUE TITLE
ForEach.reduceIdentity / sum is somewhat confusing

### ISSUE THREAD

**Issue by TimPigden** [zio/zio-prelude#884]
the whole use of ForEach is non-obvious (a documentation issue) and when trying to use the ForEach sum function there's a name collision with the scala standard collections sum - resulting (in my combination of imports at least) in the wrong sum being used. 
Thus the .sum is more or less pointless. And it replicates the function of reduceIdentity

But reduceIdentity is absolutely not an obvious name. For a start, the programmer in question has to realise that there is an identity in implicit scope and then that it wants to be reduced - "reduce" probably being in the category of names considered "unergonomic" perhaps?

I'm not sure what the solution here is. And I appreciate that the Identity in question could be multiplication.

Maybe combineAll - like in cats would be easiest. Certainly it would save having to change code if converting.

**Comment by sideeffffect** [comment]
For the record, I think I like `combineAll`, it aligns well with the `combine` method on `Associative`.

**Comment by adamgfraser** [comment]
Yeah, I think we could do that or something like `concatenate`.
