### ISSUE TITLE
release version built against zio 1.0.13

### ISSUE THREAD

**Issue by domdorn** [zio/zio-prelude#897]
I ran into problems cause this library (RC8) is still depending on zio 1.0.12 and pulling in 1.0.12 versions of zio-macros that for some reason didn't get replaced with the 1.0.13 version by sbt. I ended up having two versions of zio-test and their zio-test-macros and got runtime errors in IntelliJ when trying to run my tests.

Please release a version that depends on 1.0.13 so others don't run into the same problem.
Thanks!

**Comment by adamgfraser** [comment]
Thanks for the nudge! Just did a release!
