### ISSUE TITLE
Validation.validateAll() for Sets?

### ISSUE THREAD

**Issue by BalduinLandolt** [zio/zio-prelude#945]
I don't know if that's easily possible, but I'd find it very handy to be able to use `Validation.validateAll()` on Sets, not just on Lists.

I find myself often having a `Set[Validation[E, A]]` which I want to turn into `Validation[E, Set[A]]`. Currently I have to do `Validation.validateAll(set.toList).map(_.toSet)` which works, but it feels unnecessary cumbersome.

**Comment by adamgfraser** [comment]
Will take a look at this.

**Comment by BalduinLandolt** [comment]
If you think it might be an easy one, I'd be happy to contribute (though I might need pointers on where to start, still new to the ZIO ecosystem).

**Comment by adamgfraser** [comment]
Just added it. The only tricky thing is that normally `validateAll` is implemented in terms of the `ForEach` functional abstraction, but that does not apply to sets. We can work around this by just implementing a specialized version of the method directly much as you did.

**Comment by BalduinLandolt** [comment]
great, thanks!
